call ..\setdirs.bat
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include   asifile.cpp -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\vc\bin\link.exe  -out:asifile.exe -fixed    -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG asifile.obj  user32.lib gdi32.lib kernel32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  audiocd.c  -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\vc\bin\link.exe  -out:audiocd.exe -fixed    -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG audiocd.obj  user32.lib gdi32.lib kernel32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  sstest.c  -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\vc\bin\link.exe  -out:sstest.exe -fixed    -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG sstest.obj  user32.lib gdi32.lib kernel32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  digplay.c  -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\vc\bin\link.exe  -out:digplay.exe -fixed    -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG digplay.obj  user32.lib gdi32.lib kernel32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  xmiplay.c  -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\vc\bin\link.exe  -out:xmiplay.exe -fixed    -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG xmiplay.obj  user32.lib gdi32.lib kernel32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  play.c  -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\vc\bin\link.exe  -out:play.exe -fixed    -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG play.obj  user32.lib gdi32.lib kernel32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  streamer.c  -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\vc\bin\link.exe  -out:streamer.exe -fixed    -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG streamer.obj  user32.lib gdi32.lib kernel32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  dlsplay.c  -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\vc\bin\link.exe  -out:dlsplay.exe -fixed    -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG dlsplay.obj  user32.lib gdi32.lib kernel32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include   filter.cpp -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\vc\bin\link.exe  -out:filter.exe -fixed    -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG filter.obj  user32.lib gdi32.lib kernel32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include   custom_filter.cpp -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\vc\bin\link.exe  -out:custom_filter.exe -fixed    -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG custom_filter.obj  user32.lib gdi32.lib kernel32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include   multiflt.cpp -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\vc\bin\link.exe  -out:multiflt.exe -fixed    -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG multiflt.obj  user32.lib gdi32.lib kernel32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  record.c  -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\vc\bin\link.exe  -out:record.exe -fixed    -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG record.obj  user32.lib gdi32.lib kernel32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  demo.c  -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\common7\tools\bin\rc.exe  -i%MSVC8Dir%\vc\atlmfc\include -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include -I..\sdk -fo demo.res demo.rc
%MSVC8Dir%\vc\bin\link.exe  -out:demo.exe -fixed  -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG demo.obj demo.res user32.lib gdi32.lib kernel32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include   examms.cpp -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\common7\tools\bin\rc.exe  -i%MSVC8Dir%\vc\atlmfc\include -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include -I..\sdk -fo examms.res examms.rc
%MSVC8Dir%\vc\bin\link.exe  -out:examms.exe -fixed  -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG examms.obj examms.res user32.lib gdi32.lib kernel32.lib libcmt.lib -libpath:..\..\lib mss32.lib comctl32.lib comdlg32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  msschat.c  -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\common7\tools\bin\rc.exe  -i%MSVC8Dir%\vc\atlmfc\include -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include -I..\sdk -fo msschat.res msschat.rc
%MSVC8Dir%\vc\bin\link.exe  -out:msschat.exe -fixed  -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG msschat.obj msschat.res user32.lib gdi32.lib kernel32.lib libcmt.lib -libpath:..\..\lib mss32.lib comctl32.lib comdlg32.lib wsock32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include   msschtc.cpp -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\common7\tools\bin\rc.exe  -i%MSVC8Dir%\vc\atlmfc\include -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include -I..\sdk -fo msschtc.res msschtc.rc
%MSVC8Dir%\vc\bin\link.exe  -out:msschtc.exe -fixed  -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG msschtc.obj msschtc.res user32.lib gdi32.lib kernel32.lib libcmt.lib -libpath:..\..\lib mss32.lib comctl32.lib comdlg32.lib wsock32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include   msschts.cpp -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\common7\tools\bin\rc.exe  -i%MSVC8Dir%\vc\atlmfc\include -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include -I..\sdk -fo msschts.res msschts.rc
%MSVC8Dir%\vc\bin\link.exe  -out:msschts.exe -fixed  -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG msschts.obj msschts.res user32.lib gdi32.lib kernel32.lib libcmt.lib -libpath:..\..\lib mss32.lib comctl32.lib comdlg32.lib wsock32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  quick.c  -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\common7\tools\bin\rc.exe  -i%MSVC8Dir%\vc\atlmfc\include -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include -I..\sdk -fo quick.res quick.rc
%MSVC8Dir%\vc\bin\link.exe  -out:quick.exe -fixed  -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG quick.obj quick.res user32.lib gdi32.lib kernel32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include   eax4exam.cpp -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\vc\bin\link.exe  -out:eax4exam.exe -fixed  -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG eax4exam.obj  user32.lib gdi32.lib kernel32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:%DX9Path%\lib
