# cmake/spv_to_header.cmake
# Converts a SPIR-V binary file into a C header containing a uint32_t array.
# Called by CMakeLists.txt via:
#   cmake -DINPUT=foo.spv -DOUTPUT=foo.spv.h -DARRAY_NAME=foo_spv -P spv_to_header.cmake

cmake_minimum_required(VERSION 3.20)

file(READ "${INPUT}" SPV_BYTES HEX)

# Split into individual byte pairs
string(LENGTH "${SPV_BYTES}" HEX_LEN)
math(EXPR BYTE_COUNT "${HEX_LEN} / 2")

# Build uint32_t array entries (little-endian; SPIR-V stores words LE)
set(ARRAY_CONTENT "")
set(i 0)
while(i LESS ${BYTE_COUNT})
    math(EXPR b0 "${i} * 2")
    math(EXPR b1 "${b0} + 2")
    math(EXPR b2 "${b0} + 4")
    math(EXPR b3 "${b0} + 6")

    string(SUBSTRING "${SPV_BYTES}" ${b0} 2 byte0)
    math(EXPR next1 "${i} + 1")
    math(EXPR next2 "${i} + 2")
    math(EXPR next3 "${i} + 3")

    if(next1 LESS ${BYTE_COUNT})
        string(SUBSTRING "${SPV_BYTES}" ${b1} 2 byte1)
    else()
        set(byte1 "00")
    endif()
    if(next2 LESS ${BYTE_COUNT})
        string(SUBSTRING "${SPV_BYTES}" ${b2} 2 byte2)
    else()
        set(byte2 "00")
    endif()
    if(next3 LESS ${BYTE_COUNT})
        string(SUBSTRING "${SPV_BYTES}" ${b3} 2 byte3)
    else()
        set(byte3 "00")
    endif()

    set(ARRAY_CONTENT "${ARRAY_CONTENT}    0x${byte3}${byte2}${byte1}${byte0}u,\n")
    math(EXPR i "${i} + 4")
endwhile()

math(EXPR WORD_COUNT "(${BYTE_COUNT} + 3) / 4")

# Write header
file(WRITE "${OUTPUT}"
"// Auto-generated by spv_to_header.cmake — do not edit manually.
// Source: ${INPUT}
#pragma once
#include <cstdint>
static const uint32_t ${ARRAY_NAME}[${WORD_COUNT}] = {
${ARRAY_CONTENT}};
static const std::size_t ${ARRAY_NAME}_size = sizeof(${ARRAY_NAME});
")

message(STATUS "Generated ${OUTPUT} (${WORD_COUNT} words from ${BYTE_COUNT} bytes)")
