call ..\setdirs.bat
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__  -DUSE_MSS -GS -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  mssqapi.c midilist.c midi2xmi.c dlshl.c msscd.c mssdbg.c mssxdig.c mssxmidi.c msssys.c win32_rad_except.c mss.cpp rib.cpp m3d.cpp flt.cpp dls1pars.cpp dls1syn.cpp dlsfile.cpp miscutil.cpp mssadpcm.cpp dlslist.cpp mssstrm.cpp mssutil.cpp wavefile.cpp mssinput.cpp mssdig.cpp mix.cpp synth.cpp -D__RADINDLL__ -I%DX9Path%\include
%MSVC8Dir%\vc\bin\ml.exe  -nologo -Cp -c -W2 -DMASM  -safeseh -coff -Zi mssa32.asm win32_rad_except_safeseh.asm
%MSVC8Dir%\common7\tools\bin\rc.exe  -i%MSVC8Dir%\vc\atlmfc\include -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  -fo mss.res mss.rc
%MSVC8Dir%\vc\bin\link.exe  -out:mss32.dll -dll -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG  -base:0x21100000 mssa32.obj mss.obj rib.obj m3d.obj flt.obj mssqapi.obj dls1pars.obj dls1syn.obj dlsfile.obj miscutil.obj mssadpcm.obj dlslist.obj midilist.obj midi2xmi.obj dlshl.obj mssstrm.obj msscd.obj mssdbg.obj mssxdig.obj mssxmidi.obj mssutil.obj wavefile.obj mssinput.obj mssdig.obj msssys.obj mix.obj win32_rad_except.obj synth.obj win32_rad_except_safeseh.obj mss.res user32.lib gdi32.lib kernel32.lib libcmt.lib winmm.lib ksuser.lib -def:mss32.def
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__  -DUSE_MSS -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  mssdsp.c ribdll.c radlibc.c bandpass.cpp allpass.cpp capture.cpp chorus.cpp compress.cpp flange.cpp highpass.cpp lowpass.cpp parmeq.cpp phaser.cpp reson.cpp ringmod.cpp delay.cpp shelfeq.cpp volramp.cpp gainblk.cpp -D__RADINDLL__ -I%DX9Path%\include
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__  -DUSE_MSS -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  C:/devel/projects/shared/rtl/radlibc.c -D__RADINDLL__ -I%DX9Path%\include
%MSVC8Dir%\common7\tools\bin\rc.exe  -i%MSVC8Dir%\vc\atlmfc\include -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  -fo mss.res mss.rc
%MSVC8Dir%\vc\bin\link.exe  -out:mssdsp.flt -dll -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG  -base:0x24100000 mssdsp.obj ribdll.obj bandpass.obj allpass.obj capture.obj chorus.obj compress.obj flange.obj highpass.obj lowpass.obj parmeq.obj phaser.obj reson.obj ringmod.obj delay.obj shelfeq.obj volramp.obj gainblk.obj radlibc.obj mss.res user32.lib gdi32.lib kernel32.lib mss32.lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__  -DUSE_MSS -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  bitrate.c bitwise.c block.c codebook.c envelope.c floor0.c floor1.c framing.c info.c lpc.c lsp.c mapping0.c oggmdct.c oggpsy.c oggreg.c oggsyn.c oggwin.c res0.c sharedbook.c smallft.c ribdll.c radlibc.c oggapi.cpp -D__RADINDLL__ -I%DX9Path%\include
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__  -DUSE_MSS -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  C:/devel/projects/shared/rtl/radlibc.c -D__RADINDLL__ -I%DX9Path%\include
%MSVC8Dir%\vc\bin\link.exe  -out:mssogg.asi -dll -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG  -base:0x26f00000 oggapi.obj bitrate.obj bitwise.obj block.obj codebook.obj envelope.obj floor0.obj floor1.obj framing.obj info.obj lpc.obj lsp.obj mapping0.obj oggmdct.obj oggpsy.obj oggreg.obj oggsyn.obj oggwin.obj res0.obj sharedbook.obj smallft.obj ribdll.obj radlibc.obj  user32.lib gdi32.lib kernel32.lib mss32.lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__  -DUSE_MSS -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  ribdll.c radlibc.c mp3dec.cpp Mp3api.cpp -D__RADINDLL__ -I%DX9Path%\include
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__  -DUSE_MSS -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  C:/devel/projects/shared/rtl/radlibc.c -D__RADINDLL__ -I%DX9Path%\include
%MSVC8Dir%\vc\bin\ml.exe  -nologo -Cp -c -W2 -DMASM  -safeseh -coff -Zi math_a.asm math_sse.asm math_amd.asm
%MSVC8Dir%\vc\bin\link.exe  -out:mssmp3.asi -dll -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG  -base:0x26f00000 mp3dec.obj ribdll.obj Mp3api.obj math_a.obj math_sse.obj math_amd.obj radlibc.obj  user32.lib gdi32.lib kernel32.lib mss32.lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__  -DUSE_MSS -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  ribdll.c radlibc.c msseax2.cpp msseax3.cpp msseax4.cpp -D__RADINDLL__ -I%DX9Path%\include
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__  -DUSE_MSS -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  C:/devel/projects/shared/rtl/radlibc.c -D__RADINDLL__ -I%DX9Path%\include
%MSVC8Dir%\vc\bin\link.exe  -out:msseax.flt -dll -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG  -base:0x22300000 msseax2.obj msseax3.obj msseax4.obj ribdll.obj radlibc.obj  user32.lib gdi32.lib kernel32.lib winmm.lib mss32.lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__  -DUSE_MSS -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  ribdll.c radlibc.c mssds3dh.cpp -D__RADINDLL__ -I%DX9Path%\include
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Oxb2 -O2 -DNDEBUG -D__RADFINAL__  -DUSE_MSS -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  C:/devel/projects/shared/rtl/radlibc.c -D__RADINDLL__ -I%DX9Path%\include
%MSVC8Dir%\vc\bin\link.exe  -out:mssds3d.flt -dll -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG  -base:0x22300000 mssds3dh.obj ribdll.obj radlibc.obj  user32.lib gdi32.lib kernel32.lib winmm.lib %DX9Path%\lib\dxguid.lib mss32.lib
