#pragma once
#ifndef MAPCOLOURINDEXES_H
#define MAPCOLOURINDEXES_H

enum MapColourIndexs
{
	NONE = 0,
	CIVILIANS = 15,
	MARKER_STONE = 0x88,
	UNPOSSESSED_BUILDING = 0x888,
	SPELLS = 3840,
	UNPOSSESSED_BUILDING2 = 0xf0f,
	CREATURE = 4095
};

#endif //MAPCOLOURINDEXES_H