#pragma once

//#include "engine/defs.h"

//#include "stdafx.h"

//#include <dir.h>

//#include <vld.h>//only for debug

#include <array>
#include <typeinfo>

#include "utilities/DataFileIO.h"
#include "utilities/BitmapIO.h"

#include "engine/UVTable_D4350.h"
#include "engine/Type_D404C.h"
#include "engine/Type_D94F0_Bldgprmbuffer.h"
#include "engine/Type_D93C0_Bldgprmbuffer.h"
#include "engine/Type_MapScreenPortals_E17CC.h"
#include "engine/Type_SecretMapScreenPortals_E2970.h"
#include "engine/Basic.h"
#include "engine/Sound.h"
#include "engine/Type_Animations.h"
#include "engine/Animation.h"
#include "engine/GameRenderOriginal.h"
#include "engine/GameRenderHD.h"
#include "engine/GameRenderNG.h"
#include "engine/GameRenderGL.h"
#include "engine/GameBitmap.h"
#include "engine/GameBitmapIndexes.h"
#include "engine/GameUiConstants.h"
#include "engine/LangTextIndexes.h"
#include "engine/GameState.h"
#include "engine/MenuState.h"

#include "engine/Terrain.h"

#include "portability/port_net.h"
#include "portability/InputRecorder.h"

//#define __CFSHL__(x, y) (x<<y)
//#define __CFSHL__(x, y) 1
/*int32_t __CFSHL__(uint32_t x, uint32_t y) {
	return 1;
}*/
//myprintf("invalid_operation:__CFSHL__(x, y)")
//#define __RCR__(x, y) printf("invalid_operation:__RCR__(x, y)")
//#define __RCL__(x, y) printf("invalid_operation:__RCL__(x, y)")
//#define __ROL4__(x, y) __ROL__(x, y)       // Rotate left
//#define __ROR4__(x, y) __ROR__(x, y)       // Rotate left

#include "engine/sub_main_mouse.h"
//#include "engine/ail_sound.h"

/* This file has been generated by the Hex-Rays decompiler.
Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

Detected compiler: Watcom C++
*/

/*int sub_main(int argc, char **argv, char **envp);
int sub_97F90(x_DWORD *a1);
int sub_980D0(x_DWORD *a1, int a2);
int sub_98170(x_DWORD *a1, int a2, int a3);
int sub_A158B(int a1, __int16 a2, x_WORD *a3, x_WORD *a4);
bool sub_A4CB0();
int sub_A4F10(int a1, char a2, char a3, char a4);
x_DWORD * sub_A5850(int a1, char a2, unsigned int a3, signed int a4, int a5);*/

#ifndef SUB_MAIN_ACTIVE
#define SUB_MAIN_ACTIVE

extern InputRecorder* m_InputRecorder;

void begin_plugin();
void preconvert();
void initposistruct();
void sub_56210_process_command_line(int a1, char** a2);
int sub_56730_clean_memory();
int sub_8B5A0();
int sub_8B770();
int sub_9B234(int* a1);
void sub_75900();
int sub_53CF0_access(const char* a1);
void sub_560D0_create_sound_dir();
bool sub_53EF0_fileexist(const char* path, const char* path2);
char LoadFilesFromCDAndGameData(const char* cdPath, const char* gamePath, const char* fileName);
bool sub_53F60(const char* a1);
void sub_8C2CD();
void NetworkAllocation2_5C430();
Scene GetCurrentScene();
void SetCurrentScene(const Scene scene);
uint8_t sub_53D10_create_nether_subdir(const std::string& gameDir, const std::string& subDir);
void Initialize();

void StartRecording(const char* outputFileName);
void StopRecording();
void StartPlayback(const char* inputFileName);
void StopPlayback();
bool IsRecordingOrPlaying();
bool IsRecording();

int sub_main(int argc, char** argv, char** envp);
#endif //SUB_MAIN_ACTIVE