call ..\setdirs.bat
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Zi -wd4748 -D_DEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include  milesstu.c  -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\common7\tools\bin\rc.exe  -i%MSVC8Dir%\vc\atlmfc\include -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include -I..\sdk -fo milesstu.res milesstu.rc
%MSVC8Dir%\vc\bin\link.exe  -out:milesstu.exe -fixed  -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG milesstu.obj milesstu.res user32.lib gdi32.lib kernel32.lib libcmtd.lib -libpath:..\..\lib mss32.lib shell32.lib comdlg32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Zi -wd4748 -D_DEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include   makeloop.cpp -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\vc\bin\link.exe  -out:makeloop.exe -fixed    -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG makeloop.obj  user32.lib gdi32.lib kernel32.lib libcmtd.lib -libpath:..\..\lib mss32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Zi -wd4748 -D_DEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include   milesply.cpp -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\common7\tools\bin\rc.exe  -i%MSVC8Dir%\vc\atlmfc\include -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include -I..\sdk -fo milesply.res milesply.rc
%MSVC8Dir%\vc\bin\link.exe  -out:milesply.exe -fixed  -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG milesply.obj milesply.res user32.lib gdi32.lib kernel32.lib libcmtd.lib -libpath:..\..\lib mss32.lib comdlg32.lib comctl32.lib mss32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Zi -wd4748 -D_DEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include   milesply.cpp -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\common7\tools\bin\rc.exe  -i%MSVC8Dir%\vc\atlmfc\include -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include -I..\sdk -fo milesply.res milesply.rc
%MSVC8Dir%\vc\bin\link.exe  -out:milesply.exe -fixed    -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG milesply.obj milesply.res user32.lib gdi32.lib kernel32.lib libcmtd.lib -libpath:..\..\lib mss32.lib comdlg32.lib comctl32.lib mss32.lib -LIBPATH:%DX9Path%\lib
%MSVC8Dir%\vc\bin\cl.exe  -nologo -c -Oi -GF -Gm- -Gy -GR- -EHs- -EHa- -EHc- -fp:fast -QIfist -Gs- -GS -Zp4 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -Zi -wd4748 -D_DEBUG -D__RADFINAL__ -GL -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include   midiechw.cpp -D__RADINEXE__ -I..\sdk -I%DX9Path%\include
%MSVC8Dir%\common7\tools\bin\rc.exe  -i%MSVC8Dir%\vc\atlmfc\include -I%MSVC8Dir%\vc\include -I%MSVC8Dir%\vc\platformsdk\include -I..\sdk -fo midiechw.res midiechw.rc
%MSVC8Dir%\vc\bin\link.exe  -out:midiechw.exe -fixed  -nologo -opt:ref -opt:nowin98 -map -libpath:%MSVC8Dir%\vc\lib -libpath:%MSVC8Dir%\vc\platformsdk\lib -nodefaultlib -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -manifest:no -nxcompat -safeseh -LTCG midiechw.obj midiechw.res user32.lib gdi32.lib kernel32.lib libcmtd.lib -libpath:..\..\lib mss32.lib winmm.lib dsound.lib comdlg32.lib -LIBPATH:%DX9Path%\lib
